# Generated by Django 3.1.1 on 2020-11-21 14:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('img_url', models.URLField(max_length=512)),
                ('min_playing_time', models.IntegerField()),
                ('max_playing_time', models.IntegerField()),
                ('complexity_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
            ],
        ),
    ]
