# Generated by Django 3.1.1 on 2020-11-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201121_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='deals',
            new_name='deal',
        ),
    ]
