# Generated by Django 3.1.1 on 2020-11-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201127_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
